// This file is auto-generated by @hey-api/openapi-ts

export const AssetSummaryResponseSchema = {
    properties: {
        cash: {
            type: 'integer',
            title: 'Cash'
        },
        property_value: {
            type: 'integer',
            title: 'Property Value'
        },
        daily_income: {
            type: 'integer',
            title: 'Daily Income'
        },
        total_net_worth: {
            type: 'integer',
            title: 'Total Net Worth'
        },
        owned_count: {
            type: 'integer',
            title: 'Owned Count'
        }
    },
    type: 'object',
    required: ['cash', 'property_value', 'daily_income', 'total_net_worth', 'owned_count'],
    title: 'AssetSummaryResponse'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BuyPropertyResponseSchema = {
    properties: {
        property_id: {
            type: 'string',
            title: 'Property Id'
        },
        new_cash: {
            type: 'integer',
            title: 'New Cash'
        }
    },
    type: 'object',
    required: ['property_id', 'new_cash'],
    title: 'BuyPropertyResponse'
} as const;

export const ChapterMilestonePublicSchema = {
    properties: {
        chapter_id: {
            type: 'integer',
            title: 'Chapter Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        skill_type: {
            type: 'string',
            title: 'Skill Type'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        quiz_completed: {
            type: 'boolean',
            title: 'Quiz Completed'
        },
        scenario_completed: {
            type: 'boolean',
            title: 'Scenario Completed'
        },
        is_completed: {
            type: 'boolean',
            title: 'Is Completed'
        },
        is_current: {
            type: 'boolean',
            title: 'Is Current'
        }
    },
    type: 'object',
    required: ['chapter_id', 'title', 'skill_type', 'description', 'quiz_completed', 'scenario_completed', 'is_completed', 'is_current'],
    title: 'ChapterMilestonePublic'
} as const;

export const ChapterStatusResponseSchema = {
    properties: {
        completed_chapters: {
            type: 'integer',
            title: 'Completed Chapters'
        },
        income_multiplier: {
            type: 'number',
            title: 'Income Multiplier'
        },
        starter_grant_claimed: {
            type: 'boolean',
            title: 'Starter Grant Claimed'
        },
        can_claim_starter_grant: {
            type: 'boolean',
            title: 'Can Claim Starter Grant'
        },
        chapters: {
            items: {
                '$ref': '#/components/schemas/ChapterMilestonePublic'
            },
            type: 'array',
            title: 'Chapters'
        }
    },
    type: 'object',
    required: ['completed_chapters', 'income_multiplier', 'starter_grant_claimed', 'can_claim_starter_grant', 'chapters'],
    title: 'ChapterStatusResponse'
} as const;

export const ClaimStarterGrantResponseSchema = {
    properties: {
        granted_cash: {
            type: 'integer',
            title: 'Granted Cash'
        },
        new_cash: {
            type: 'integer',
            title: 'New Cash'
        }
    },
    type: 'object',
    required: ['granted_cash', 'new_cash'],
    title: 'ClaimStarterGrantResponse'
} as const;

export const EconomyMeResponseSchema = {
    properties: {
        cash: {
            type: 'integer',
            title: 'Cash'
        },
        xp: {
            type: 'integer',
            title: 'Xp'
        },
        level: {
            type: 'integer',
            title: 'Level'
        },
        streak_days: {
            type: 'integer',
            title: 'Streak Days'
        },
        pending_accrual: {
            type: 'integer',
            title: 'Pending Accrual'
        },
        bankruptcy_pending: {
            type: 'boolean',
            title: 'Bankruptcy Pending'
        },
        completed_chapters: {
            type: 'integer',
            title: 'Completed Chapters',
            default: 0
        }
    },
    type: 'object',
    required: ['cash', 'xp', 'level', 'streak_days', 'pending_accrual', 'bankruptcy_pending'],
    title: 'EconomyMeResponse'
} as const;

export const FlagItemSchema = {
    properties: {
        tag: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tag'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        detail: {
            type: 'string',
            title: 'Detail'
        }
    },
    type: 'object',
    required: ['tag', 'label', 'detail'],
    title: 'FlagItem'
} as const;

export const FraudTypeResultSchema = {
    properties: {
        correct: {
            type: 'integer',
            title: 'Correct'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['correct', 'total'],
    title: 'FraudTypeResult'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HomeDecorActionRequestSchema = {
    properties: {
        decor_id: {
            type: 'string',
            title: 'Decor Id'
        }
    },
    type: 'object',
    required: ['decor_id'],
    title: 'HomeDecorActionRequest'
} as const;

export const HomeDecorItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        cost: {
            type: 'integer',
            title: 'Cost'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        icon: {
            type: 'string',
            title: 'Icon'
        },
        is_owned: {
            type: 'boolean',
            title: 'Is Owned'
        },
        is_equipped: {
            type: 'boolean',
            title: 'Is Equipped'
        }
    },
    type: 'object',
    required: ['id', 'name', 'cost', 'description', 'icon', 'is_owned', 'is_equipped'],
    title: 'HomeDecorItemPublic'
} as const;

export const HomeFollowUpEventResponseSchema = {
    properties: {
        event_id: {
            type: 'string',
            title: 'Event Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        scenario: {
            type: 'string',
            title: 'Scenario'
        },
        verification_step: {
            type: 'string',
            title: 'Verification Step'
        },
        evidence: {
            type: 'string',
            title: 'Evidence'
        },
        is_completed: {
            type: 'boolean',
            title: 'Is Completed'
        }
    },
    type: 'object',
    required: ['event_id', 'title', 'scenario', 'verification_step', 'evidence', 'is_completed'],
    title: 'HomeFollowUpEventResponse'
} as const;

export const HouseTaskPublicSchema = {
    properties: {
        task_id: {
            type: 'string',
            title: 'Task Id'
        },
        tier_id: {
            type: 'integer',
            title: 'Tier Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        scenario: {
            type: 'string',
            title: 'Scenario'
        },
        steps: {
            items: {
                '$ref': '#/components/schemas/HouseTaskStepPublic'
            },
            type: 'array',
            title: 'Steps'
        },
        is_passed: {
            type: 'boolean',
            title: 'Is Passed'
        },
        can_proceed_to_buy: {
            type: 'boolean',
            title: 'Can Proceed To Buy'
        }
    },
    type: 'object',
    required: ['task_id', 'tier_id', 'title', 'scenario', 'steps', 'is_passed', 'can_proceed_to_buy'],
    title: 'HouseTaskPublic'
} as const;

export const HouseTaskResolveRequestSchema = {
    properties: {
        choice: {
            type: 'string',
            enum: ['official_escrow', 'private_wire'],
            title: 'Choice'
        }
    },
    type: 'object',
    required: ['choice'],
    title: 'HouseTaskResolveRequest'
} as const;

export const HouseTaskResolveResponseSchema = {
    properties: {
        is_passed: {
            type: 'boolean',
            title: 'Is Passed'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        can_buy: {
            type: 'boolean',
            title: 'Can Buy'
        }
    },
    type: 'object',
    required: ['is_passed', 'message', 'can_buy'],
    title: 'HouseTaskResolveResponse'
} as const;

export const HouseTaskStepPublicSchema = {
    properties: {
        step_id: {
            type: 'string',
            title: 'Step Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        evidence: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Evidence'
        },
        is_done: {
            type: 'boolean',
            title: 'Is Done',
            default: false
        }
    },
    type: 'object',
    required: ['step_id', 'name', 'description'],
    title: 'HouseTaskStepPublic'
} as const;

export const HouseTaskVerifyRequestSchema = {
    properties: {
        step_id: {
            type: 'string',
            title: 'Step Id'
        }
    },
    type: 'object',
    required: ['step_id'],
    title: 'HouseTaskVerifyRequest'
} as const;

export const HouseTaskVerifyResponseSchema = {
    properties: {
        step_id: {
            type: 'string',
            title: 'Step Id'
        },
        evidence: {
            type: 'string',
            title: 'Evidence'
        },
        all_steps_done: {
            type: 'boolean',
            title: 'All Steps Done'
        }
    },
    type: 'object',
    required: ['step_id', 'evidence', 'all_steps_done'],
    title: 'HouseTaskVerifyResponse'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LiquidateRequestSchema = {
    properties: {
        property_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Property Ids'
        }
    },
    type: 'object',
    required: ['property_ids'],
    title: 'LiquidateRequest'
} as const;

export const LiquidateResponseSchema = {
    properties: {
        recovered: {
            type: 'integer',
            title: 'Recovered'
        },
        new_cash: {
            type: 'integer',
            title: 'New Cash'
        },
        bankruptcy_pending: {
            type: 'boolean',
            title: 'Bankruptcy Pending'
        }
    },
    type: 'object',
    required: ['recovered', 'new_cash', 'bankruptcy_pending'],
    title: 'LiquidateResponse'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MyHomeResponseSchema = {
    properties: {
        has_house: {
            type: 'boolean',
            title: 'Has House'
        },
        house_count: {
            type: 'integer',
            title: 'House Count'
        },
        best_tier_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Best Tier Name'
        },
        decorations: {
            items: {
                '$ref': '#/components/schemas/HomeDecorItemPublic'
            },
            type: 'array',
            title: 'Decorations'
        },
        follow_up_event_unlocked: {
            type: 'boolean',
            title: 'Follow Up Event Unlocked'
        },
        follow_up_event_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Follow Up Event Title'
        },
        follow_up_event_done: {
            type: 'boolean',
            title: 'Follow Up Event Done'
        }
    },
    type: 'object',
    required: ['has_house', 'house_count', 'best_tier_name', 'decorations', 'follow_up_event_unlocked', 'follow_up_event_title', 'follow_up_event_done'],
    title: 'MyHomeResponse'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OwnedPropertyPublicSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        tier: {
            '$ref': '#/components/schemas/PropertyTierPublic'
        },
        purchased_at: {
            type: 'string',
            title: 'Purchased At'
        },
        purchase_price: {
            type: 'integer',
            title: 'Purchase Price',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'tier', 'purchased_at'],
    title: 'OwnedPropertyPublic'
} as const;

export const PretestAnswerSchema = {
    properties: {
        question_id: {
            type: 'string',
            title: 'Question Id'
        },
        selected_option: {
            type: 'string',
            title: 'Selected Option'
        }
    },
    type: 'object',
    required: ['question_id', 'selected_option'],
    title: 'PretestAnswer'
} as const;

export const PretestSubmitRequestSchema = {
    properties: {
        answers: {
            items: {
                '$ref': '#/components/schemas/PretestAnswer'
            },
            type: 'array',
            title: 'Answers'
        }
    },
    type: 'object',
    required: ['answers'],
    title: 'PretestSubmitRequest'
} as const;

export const PretestSubmitResponseSchema = {
    properties: {
        results_by_type: {
            additionalProperties: {
                '$ref': '#/components/schemas/FraudTypeResult'
            },
            type: 'object',
            title: 'Results By Type'
        },
        weakest_type: {
            type: 'string',
            title: 'Weakest Type'
        },
        ready_for_game: {
            type: 'boolean',
            title: 'Ready For Game'
        }
    },
    type: 'object',
    required: ['results_by_type', 'weakest_type', 'ready_for_game'],
    title: 'PretestSubmitResponse'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const PropertiesListResponseSchema = {
    properties: {
        tiers: {
            items: {
                '$ref': '#/components/schemas/PropertyTierPublic'
            },
            type: 'array',
            title: 'Tiers'
        },
        owned: {
            items: {
                '$ref': '#/components/schemas/OwnedPropertyPublic'
            },
            type: 'array',
            title: 'Owned'
        }
    },
    type: 'object',
    required: ['tiers', 'owned'],
    title: 'PropertiesListResponse'
} as const;

export const PropertyTierPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        svg_key: {
            type: 'string',
            title: 'Svg Key'
        },
        price: {
            type: 'integer',
            title: 'Price'
        },
        daily_income: {
            type: 'integer',
            title: 'Daily Income'
        },
        unlock_level: {
            type: 'integer',
            title: 'Unlock Level'
        }
    },
    type: 'object',
    required: ['id', 'name', 'svg_key', 'price', 'daily_income', 'unlock_level'],
    title: 'PropertyTierPublic'
} as const;

export const QuizAnswerRequestSchema = {
    properties: {
        item_id: {
            type: 'string',
            maxLength: 64,
            title: 'Item Id'
        },
        guess_is_scam: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Guess Is Scam'
        },
        selected_option: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 16
                },
                {
                    type: 'null'
                }
            ],
            title: 'Selected Option'
        },
        selected_tags: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        maxLength: 32
                    },
                    type: 'array',
                    maxItems: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Selected Tags'
        },
        pairs: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string',
                        maxLength: 64
                    },
                    propertyNames: {
                        maxLength: 64
                    },
                    type: 'object',
                    maxProperties: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pairs'
        },
        session_id: {
            type: 'string',
            title: 'Session Id'
        }
    },
    type: 'object',
    required: ['item_id', 'session_id'],
    title: 'QuizAnswerRequest'
} as const;

export const QuizCompleteRequestSchema = {
    properties: {
        session_id: {
            type: 'string',
            title: 'Session Id'
        }
    },
    type: 'object',
    required: ['session_id'],
    title: 'QuizCompleteRequest'
} as const;

export const QuizCompleteResponseSchema = {
    properties: {
        correct_count: {
            type: 'integer',
            title: 'Correct Count'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        best_streak: {
            type: 'integer',
            title: 'Best Streak'
        },
        cash_earned: {
            type: 'integer',
            title: 'Cash Earned'
        },
        xp_earned: {
            type: 'integer',
            title: 'Xp Earned'
        },
        weakness_summary: {
            items: {
                '$ref': '#/components/schemas/WeaknessSummaryItem'
            },
            type: 'array',
            title: 'Weakness Summary'
        }
    },
    type: 'object',
    required: ['correct_count', 'total', 'best_streak', 'cash_earned', 'xp_earned', 'weakness_summary'],
    title: 'QuizCompleteResponse'
} as const;

export const QuizDeckResponseSchema = {
    properties: {
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        items: {
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/QuizVerdictPublic'
                    },
                    {
                        '$ref': '#/components/schemas/QuizVerificationPublic'
                    },
                    {
                        '$ref': '#/components/schemas/QuizTacticsPublic'
                    },
                    {
                        '$ref': '#/components/schemas/QuizMatchPublic'
                    }
                ],
                discriminator: {
                    propertyName: 'type',
                    mapping: {
                        match: '#/components/schemas/QuizMatchPublic',
                        tactics: '#/components/schemas/QuizTacticsPublic',
                        verdict: '#/components/schemas/QuizVerdictPublic',
                        verification: '#/components/schemas/QuizVerificationPublic'
                    }
                }
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['session_id', 'items'],
    title: 'QuizDeckResponse'
} as const;

export const QuizMatchAnswerResponseSchema = {
    properties: {
        type: {
            type: 'string',
            const: 'match',
            title: 'Type',
            default: 'match'
        },
        correct: {
            type: 'boolean',
            title: 'Correct'
        },
        results: {
            items: {
                '$ref': '#/components/schemas/QuizMatchPairResult'
            },
            type: 'array',
            title: 'Results'
        },
        tag_details: {
            items: {
                '$ref': '#/components/schemas/QuizWeaknessDetail'
            },
            type: 'array',
            title: 'Tag Details'
        }
    },
    type: 'object',
    required: ['correct', 'results', 'tag_details'],
    title: 'QuizMatchAnswerResponse'
} as const;

export const QuizMatchPairResultSchema = {
    properties: {
        pair_id: {
            type: 'string',
            title: 'Pair Id'
        },
        correct_tag: {
            type: 'string',
            title: 'Correct Tag'
        },
        correct: {
            type: 'boolean',
            title: 'Correct'
        }
    },
    type: 'object',
    required: ['pair_id', 'correct_tag', 'correct'],
    title: 'QuizMatchPairResult'
} as const;

export const QuizMatchPromptSchema = {
    properties: {
        pair_id: {
            type: 'string',
            title: 'Pair Id'
        },
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: ['pair_id', 'text'],
    title: 'QuizMatchPrompt'
} as const;

export const QuizMatchPublicSchema = {
    properties: {
        item_id: {
            type: 'string',
            title: 'Item Id'
        },
        type: {
            type: 'string',
            const: 'match',
            title: 'Type',
            default: 'match'
        },
        question: {
            type: 'string',
            title: 'Question'
        },
        match_prompts: {
            items: {
                '$ref': '#/components/schemas/QuizMatchPrompt'
            },
            type: 'array',
            title: 'Match Prompts'
        },
        match_targets: {
            items: {
                '$ref': '#/components/schemas/QuizMatchTarget'
            },
            type: 'array',
            title: 'Match Targets'
        }
    },
    type: 'object',
    required: ['item_id', 'question', 'match_prompts', 'match_targets'],
    title: 'QuizMatchPublic'
} as const;

export const QuizMatchTargetSchema = {
    properties: {
        tag: {
            type: 'string',
            title: 'Tag'
        },
        label: {
            type: 'string',
            title: 'Label'
        }
    },
    type: 'object',
    required: ['tag', 'label'],
    title: 'QuizMatchTarget'
} as const;

export const QuizRedFlagSchema = {
    properties: {
        tag: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tag'
        },
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: ['tag', 'text'],
    title: 'QuizRedFlag'
} as const;

export const QuizTacticsAnswerResponseSchema = {
    properties: {
        type: {
            type: 'string',
            const: 'tactics',
            title: 'Type',
            default: 'tactics'
        },
        correct: {
            type: 'boolean',
            title: 'Correct'
        },
        correct_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Correct Tags'
        },
        missed_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Missed Tags'
        },
        extra_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Extra Tags'
        },
        tag_details: {
            items: {
                '$ref': '#/components/schemas/QuizWeaknessDetail'
            },
            type: 'array',
            title: 'Tag Details'
        }
    },
    type: 'object',
    required: ['correct', 'correct_tags', 'missed_tags', 'extra_tags', 'tag_details'],
    title: 'QuizTacticsAnswerResponse'
} as const;

export const QuizTacticsOptionSchema = {
    properties: {
        tag: {
            type: 'string',
            title: 'Tag'
        },
        label: {
            type: 'string',
            title: 'Label'
        }
    },
    type: 'object',
    required: ['tag', 'label'],
    title: 'QuizTacticsOption'
} as const;

export const QuizTacticsPublicSchema = {
    properties: {
        item_id: {
            type: 'string',
            title: 'Item Id'
        },
        type: {
            type: 'string',
            const: 'tactics',
            title: 'Type',
            default: 'tactics'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        narrative: {
            type: 'string',
            title: 'Narrative'
        },
        question: {
            type: 'string',
            title: 'Question'
        },
        options: {
            items: {
                '$ref': '#/components/schemas/QuizTacticsOption'
            },
            type: 'array',
            title: 'Options'
        }
    },
    type: 'object',
    required: ['item_id', 'title', 'narrative', 'question', 'options'],
    title: 'QuizTacticsPublic'
} as const;

export const QuizVerdictAnswerResponseSchema = {
    properties: {
        type: {
            type: 'string',
            const: 'verdict',
            title: 'Type',
            default: 'verdict'
        },
        correct: {
            type: 'boolean',
            title: 'Correct'
        },
        is_scam: {
            type: 'boolean',
            title: 'Is Scam'
        },
        red_flags: {
            items: {
                '$ref': '#/components/schemas/QuizRedFlag'
            },
            type: 'array',
            title: 'Red Flags'
        },
        provenance: {
            type: 'string',
            title: 'Provenance'
        },
        tag_details: {
            items: {
                '$ref': '#/components/schemas/QuizWeaknessDetail'
            },
            type: 'array',
            title: 'Tag Details'
        }
    },
    type: 'object',
    required: ['correct', 'is_scam', 'red_flags', 'provenance', 'tag_details'],
    title: 'QuizVerdictAnswerResponse'
} as const;

export const QuizVerdictPublicSchema = {
    properties: {
        item_id: {
            type: 'string',
            title: 'Item Id'
        },
        type: {
            type: 'string',
            const: 'verdict',
            title: 'Type',
            default: 'verdict'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        narrative: {
            type: 'string',
            title: 'Narrative'
        }
    },
    type: 'object',
    required: ['item_id', 'title', 'narrative'],
    title: 'QuizVerdictPublic'
} as const;

export const QuizVerificationAnswerResponseSchema = {
    properties: {
        type: {
            type: 'string',
            const: 'verification',
            title: 'Type',
            default: 'verification'
        },
        correct: {
            type: 'boolean',
            title: 'Correct'
        },
        explanation: {
            type: 'string',
            title: 'Explanation'
        },
        tag_details: {
            items: {
                '$ref': '#/components/schemas/QuizWeaknessDetail'
            },
            type: 'array',
            title: 'Tag Details'
        }
    },
    type: 'object',
    required: ['correct', 'explanation', 'tag_details'],
    title: 'QuizVerificationAnswerResponse'
} as const;

export const QuizVerificationOptionSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: ['key', 'text'],
    title: 'QuizVerificationOption'
} as const;

export const QuizVerificationPublicSchema = {
    properties: {
        item_id: {
            type: 'string',
            title: 'Item Id'
        },
        type: {
            type: 'string',
            const: 'verification',
            title: 'Type',
            default: 'verification'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        narrative: {
            type: 'string',
            title: 'Narrative'
        },
        question: {
            type: 'string',
            title: 'Question'
        },
        options: {
            items: {
                '$ref': '#/components/schemas/QuizVerificationOption'
            },
            type: 'array',
            title: 'Options'
        }
    },
    type: 'object',
    required: ['item_id', 'title', 'narrative', 'question', 'options'],
    title: 'QuizVerificationPublic'
} as const;

export const QuizWeaknessDetailSchema = {
    properties: {
        tag: {
            type: 'string',
            title: 'Tag'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        suggestion: {
            type: 'string',
            title: 'Suggestion'
        }
    },
    type: 'object',
    required: ['tag', 'label', 'suggestion'],
    title: 'QuizWeaknessDetail'
} as const;

export const ScenarioDetailSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        fraud_type: {
            type: 'string',
            title: 'Fraud Type'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        avatar: {
            type: 'string',
            title: 'Avatar'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        outcome: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Outcome'
        },
        player_turns: {
            type: 'integer',
            title: 'Player Turns'
        },
        max_turns: {
            type: 'integer',
            title: 'Max Turns'
        },
        history: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'History'
        },
        available_tools: {
            items: {
                '$ref': '#/components/schemas/ScenarioToolItem'
            },
            type: 'array',
            title: 'Available Tools',
            default: []
        },
        unlocked_evidence: {
            items: {
                '$ref': '#/components/schemas/ScenarioEvidenceItem'
            },
            type: 'array',
            title: 'Unlocked Evidence',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'fraud_type', 'display_name', 'avatar', 'status', 'outcome', 'player_turns', 'max_turns', 'history'],
    title: 'ScenarioDetail'
} as const;

export const ScenarioEvidenceItemSchema = {
    properties: {
        tool_id: {
            type: 'string',
            title: 'Tool Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['tool_id', 'title', 'content'],
    title: 'ScenarioEvidenceItem'
} as const;

export const ScenarioInboxItemSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        fraud_type: {
            type: 'string',
            title: 'Fraud Type'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        avatar: {
            type: 'string',
            title: 'Avatar'
        },
        preview: {
            type: 'string',
            title: 'Preview'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        outcome: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Outcome'
        },
        unread: {
            type: 'boolean',
            title: 'Unread'
        }
    },
    type: 'object',
    required: ['id', 'fraud_type', 'display_name', 'avatar', 'preview', 'status', 'outcome', 'unread'],
    title: 'ScenarioInboxItem'
} as const;

export const ScenarioJudgeRequestSchema = {
    properties: {
        action: {
            type: 'string',
            enum: ['report', 'comply', 'safe_exit'],
            title: 'Action'
        }
    },
    type: 'object',
    required: ['action'],
    title: 'ScenarioJudgeRequest'
} as const;

export const ScenarioJudgeResponseSchema = {
    properties: {
        outcome: {
            type: 'string',
            title: 'Outcome'
        },
        true_role: {
            type: 'string',
            title: 'True Role'
        },
        persona_name: {
            type: 'string',
            title: 'Persona Name'
        },
        flags: {
            items: {
                '$ref': '#/components/schemas/FlagItem'
            },
            type: 'array',
            title: 'Flags'
        },
        cash_delta: {
            type: 'integer',
            title: 'Cash Delta'
        },
        xp_delta: {
            type: 'integer',
            title: 'Xp Delta'
        },
        new_cash: {
            type: 'integer',
            title: 'New Cash'
        },
        triggers_forced_sell: {
            type: 'boolean',
            title: 'Triggers Forced Sell'
        },
        case_provenance: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Case Provenance'
        },
        unlocked_evidence_count: {
            type: 'integer',
            title: 'Unlocked Evidence Count',
            default: 0
        }
    },
    type: 'object',
    required: ['outcome', 'true_role', 'persona_name', 'flags', 'cash_delta', 'xp_delta', 'new_cash', 'triggers_forced_sell', 'case_provenance'],
    title: 'ScenarioJudgeResponse'
} as const;

export const ScenarioMessageRequestSchema = {
    properties: {
        text: {
            type: 'string',
            maxLength: 2000,
            title: 'Text'
        }
    },
    type: 'object',
    required: ['text'],
    title: 'ScenarioMessageRequest'
} as const;

export const ScenarioMessageResponseSchema = {
    properties: {
        messages: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Messages'
        },
        decision_point: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Decision Point'
        },
        turns_left: {
            type: 'integer',
            title: 'Turns Left'
        }
    },
    type: 'object',
    required: ['messages', 'decision_point', 'turns_left'],
    title: 'ScenarioMessageResponse'
} as const;

export const ScenarioNewRequestSchema = {
    properties: {
        fraud_type: {
            type: 'string',
            title: 'Fraud Type'
        }
    },
    type: 'object',
    required: ['fraud_type'],
    title: 'ScenarioNewRequest'
} as const;

export const ScenarioToolItemSchema = {
    properties: {
        tool_id: {
            type: 'string',
            title: 'Tool Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    required: ['tool_id', 'name', 'description'],
    title: 'ScenarioToolItem'
} as const;

export const ScenarioVerifyRequestSchema = {
    properties: {
        tool_id: {
            type: 'string',
            title: 'Tool Id'
        }
    },
    type: 'object',
    required: ['tool_id'],
    title: 'ScenarioVerifyRequest'
} as const;

export const ScenarioVerifyResponseSchema = {
    properties: {
        evidence: {
            '$ref': '#/components/schemas/ScenarioEvidenceItem'
        },
        already_unlocked: {
            type: 'boolean',
            title: 'Already Unlocked'
        },
        unlocked_evidence: {
            items: {
                '$ref': '#/components/schemas/ScenarioEvidenceItem'
            },
            type: 'array',
            title: 'Unlocked Evidence'
        }
    },
    type: 'object',
    required: ['evidence', 'already_unlocked', 'unlocked_evidence'],
    title: 'ScenarioVerifyResponse'
} as const;

export const SwipeAnswerRequestSchema = {
    properties: {
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        card_id: {
            type: 'string',
            title: 'Card Id'
        },
        guess_is_scam: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Guess Is Scam'
        },
        action: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['scam', 'legit', 'skip']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Action'
        }
    },
    type: 'object',
    required: ['session_id', 'card_id'],
    title: 'SwipeAnswerRequest'
} as const;

export const SwipeAnswerResponseSchema = {
    properties: {
        correct: {
            type: 'boolean',
            title: 'Correct'
        },
        is_scam: {
            type: 'boolean',
            title: 'Is Scam'
        },
        action_taken: {
            type: 'string',
            title: 'Action Taken'
        },
        explanation: {
            type: 'string',
            title: 'Explanation'
        },
        weakness_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Weakness Tags'
        },
        tag_details: {
            items: {
                '$ref': '#/components/schemas/QuizWeaknessDetail'
            },
            type: 'array',
            title: 'Tag Details'
        }
    },
    type: 'object',
    required: ['correct', 'is_scam', 'action_taken', 'explanation', 'weakness_tags', 'tag_details'],
    title: 'SwipeAnswerResponse'
} as const;

export const SwipeCardPublicSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        scenario: {
            type: 'string',
            title: 'Scenario'
        }
    },
    type: 'object',
    required: ['id', 'scenario'],
    title: 'SwipeCardPublic'
} as const;

export const SwipeCompleteRequestSchema = {
    properties: {
        session_id: {
            type: 'string',
            title: 'Session Id'
        }
    },
    type: 'object',
    required: ['session_id'],
    title: 'SwipeCompleteRequest'
} as const;

export const SwipeCompleteResponseSchema = {
    properties: {
        correct_count: {
            type: 'integer',
            title: 'Correct Count'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        best_streak: {
            type: 'integer',
            title: 'Best Streak'
        },
        cash_earned: {
            type: 'integer',
            title: 'Cash Earned'
        },
        xp_earned: {
            type: 'integer',
            title: 'Xp Earned'
        },
        weakness_summary: {
            items: {
                '$ref': '#/components/schemas/WeaknessSummaryItem'
            },
            type: 'array',
            title: 'Weakness Summary'
        }
    },
    type: 'object',
    required: ['correct_count', 'total', 'best_streak', 'cash_earned', 'xp_earned', 'weakness_summary'],
    title: 'SwipeCompleteResponse'
} as const;

export const SwipeDeckResponseSchema = {
    properties: {
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        cards: {
            items: {
                '$ref': '#/components/schemas/SwipeCardPublic'
            },
            type: 'array',
            title: 'Cards'
        }
    },
    type: 'object',
    required: ['session_id', 'cards'],
    title: 'SwipeDeckResponse'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VehiclePublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        price: {
            type: 'integer',
            title: 'Price'
        },
        is_owned: {
            type: 'boolean',
            title: 'Is Owned'
        },
        purchased_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purchased At'
        },
        follow_up_event_title: {
            type: 'string',
            title: 'Follow Up Event Title'
        },
        follow_up_event_done: {
            type: 'boolean',
            title: 'Follow Up Event Done'
        }
    },
    type: 'object',
    required: ['name', 'price', 'is_owned', 'purchased_at', 'follow_up_event_title', 'follow_up_event_done'],
    title: 'VehiclePublic'
} as const;

export const WeaknessSummaryItemSchema = {
    properties: {
        tag: {
            type: 'string',
            title: 'Tag'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['tag', 'label', 'count'],
    title: 'WeaknessSummaryItem'
} as const;