// This file is auto-generated by @hey-api/openapi-ts

export const AnswerRequestSchema = {
    properties: {
        selected_option: {
            type: 'string',
            title: 'Selected Option'
        }
    },
    type: 'object',
    required: ['selected_option'],
    title: 'AnswerRequest'
} as const;

export const AnswerResponseSchema = {
    properties: {
        answer_result: {
            '$ref': '#/components/schemas/AnswerResult'
        },
        mascot_popup: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MascotPopup'
                },
                {
                    type: 'null'
                }
            ]
        },
        next_question: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/GameResponse'
                },
                {
                    type: 'null'
                }
            ]
        },
        game_over: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/GameOverResult'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['answer_result'],
    title: 'AnswerResponse'
} as const;

export const AnswerResultSchema = {
    properties: {
        is_correct: {
            type: 'boolean',
            title: 'Is Correct'
        },
        correct_option: {
            type: 'string',
            title: 'Correct Option'
        },
        explanation: {
            type: 'string',
            title: 'Explanation'
        },
        score_earned: {
            type: 'integer',
            title: 'Score Earned'
        },
        total_score: {
            type: 'integer',
            title: 'Total Score'
        }
    },
    type: 'object',
    required: ['is_correct', 'correct_option', 'explanation', 'score_earned', 'total_score'],
    title: 'AnswerResult'
} as const;

export const AssetSummaryResponseSchema = {
    properties: {
        cash: {
            type: 'integer',
            title: 'Cash'
        },
        property_value: {
            type: 'integer',
            title: 'Property Value'
        },
        daily_income: {
            type: 'integer',
            title: 'Daily Income'
        },
        total_net_worth: {
            type: 'integer',
            title: 'Total Net Worth'
        },
        owned_count: {
            type: 'integer',
            title: 'Owned Count'
        }
    },
    type: 'object',
    required: ['cash', 'property_value', 'daily_income', 'total_net_worth', 'owned_count'],
    title: 'AssetSummaryResponse'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BuyPropertyResponseSchema = {
    properties: {
        property_id: {
            type: 'string',
            title: 'Property Id'
        },
        new_cash: {
            type: 'integer',
            title: 'New Cash'
        }
    },
    type: 'object',
    required: ['property_id', 'new_cash'],
    title: 'BuyPropertyResponse'
} as const;

export const EconomyMeResponseSchema = {
    properties: {
        cash: {
            type: 'integer',
            title: 'Cash'
        },
        xp: {
            type: 'integer',
            title: 'Xp'
        },
        level: {
            type: 'integer',
            title: 'Level'
        },
        streak_days: {
            type: 'integer',
            title: 'Streak Days'
        },
        pending_accrual: {
            type: 'integer',
            title: 'Pending Accrual'
        },
        bankruptcy_pending: {
            type: 'boolean',
            title: 'Bankruptcy Pending'
        }
    },
    type: 'object',
    required: ['cash', 'xp', 'level', 'streak_days', 'pending_accrual', 'bankruptcy_pending'],
    title: 'EconomyMeResponse'
} as const;

export const FlagItemSchema = {
    properties: {
        tag: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tag'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        detail: {
            type: 'string',
            title: 'Detail'
        }
    },
    type: 'object',
    required: ['tag', 'label', 'detail'],
    title: 'FlagItem'
} as const;

export const FraudTypeResultSchema = {
    properties: {
        correct: {
            type: 'integer',
            title: 'Correct'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['correct', 'total'],
    title: 'FraudTypeResult'
} as const;

export const GameOptionSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: ['key', 'text'],
    title: 'GameOption'
} as const;

export const GameOverResultSchema = {
    properties: {
        total_score: {
            type: 'integer',
            title: 'Total Score'
        },
        correct_rate: {
            type: 'number',
            title: 'Correct Rate'
        },
        grade: {
            type: 'string',
            title: 'Grade'
        },
        weakness_analysis: {
            items: {
                '$ref': '#/components/schemas/WeaknessDetail'
            },
            type: 'array',
            title: 'Weakness Analysis'
        },
        strength_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Strength Tags'
        }
    },
    type: 'object',
    required: ['total_score', 'correct_rate', 'grade', 'weakness_analysis', 'strength_tags'],
    title: 'GameOverResult'
} as const;

export const GameResponseSchema = {
    properties: {
        question_type: {
            type: 'string',
            enum: ['scenario', 'judgment', 'trap'],
            title: 'Question Type'
        },
        narrative: {
            type: 'string',
            title: 'Narrative'
        },
        question: {
            type: 'string',
            title: 'Question'
        },
        options: {
            items: {
                '$ref': '#/components/schemas/GameOption'
            },
            type: 'array',
            title: 'Options'
        },
        correct_option: {
            type: 'string',
            title: 'Correct Option'
        },
        explanation: {
            type: 'string',
            title: 'Explanation'
        },
        weakness_tag: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weakness Tag'
        },
        difficulty: {
            type: 'integer',
            title: 'Difficulty'
        }
    },
    type: 'object',
    required: ['question_type', 'narrative', 'question', 'options', 'correct_option', 'explanation', 'weakness_tag', 'difficulty'],
    title: 'GameResponse',
    description: 'Agent 每步回傳的統一格式'
} as const;

export const GameStartRequestSchema = {
    properties: {
        fraud_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fraud Type'
        }
    },
    type: 'object',
    title: 'GameStartRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LiquidateRequestSchema = {
    properties: {
        property_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Property Ids'
        }
    },
    type: 'object',
    required: ['property_ids'],
    title: 'LiquidateRequest'
} as const;

export const LiquidateResponseSchema = {
    properties: {
        recovered: {
            type: 'integer',
            title: 'Recovered'
        },
        new_cash: {
            type: 'integer',
            title: 'New Cash'
        },
        bankruptcy_pending: {
            type: 'boolean',
            title: 'Bankruptcy Pending'
        }
    },
    type: 'object',
    required: ['recovered', 'new_cash', 'bankruptcy_pending'],
    title: 'LiquidateResponse'
} as const;

export const MascotPopupSchema = {
    properties: {
        show: {
            type: 'boolean',
            title: 'Show'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['show', 'message'],
    title: 'MascotPopup'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OwnedPropertyPublicSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        tier: {
            '$ref': '#/components/schemas/PropertyTierPublic'
        },
        purchased_at: {
            type: 'string',
            title: 'Purchased At'
        }
    },
    type: 'object',
    required: ['id', 'tier', 'purchased_at'],
    title: 'OwnedPropertyPublic'
} as const;

export const PretestAnswerSchema = {
    properties: {
        question_id: {
            type: 'string',
            title: 'Question Id'
        },
        selected_option: {
            type: 'string',
            title: 'Selected Option'
        }
    },
    type: 'object',
    required: ['question_id', 'selected_option'],
    title: 'PretestAnswer'
} as const;

export const PretestSubmitRequestSchema = {
    properties: {
        answers: {
            items: {
                '$ref': '#/components/schemas/PretestAnswer'
            },
            type: 'array',
            title: 'Answers'
        }
    },
    type: 'object',
    required: ['answers'],
    title: 'PretestSubmitRequest'
} as const;

export const PretestSubmitResponseSchema = {
    properties: {
        results_by_type: {
            additionalProperties: {
                '$ref': '#/components/schemas/FraudTypeResult'
            },
            type: 'object',
            title: 'Results By Type'
        },
        weakest_type: {
            type: 'string',
            title: 'Weakest Type'
        },
        ready_for_game: {
            type: 'boolean',
            title: 'Ready For Game'
        }
    },
    type: 'object',
    required: ['results_by_type', 'weakest_type', 'ready_for_game'],
    title: 'PretestSubmitResponse'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const PropertiesListResponseSchema = {
    properties: {
        tiers: {
            items: {
                '$ref': '#/components/schemas/PropertyTierPublic'
            },
            type: 'array',
            title: 'Tiers'
        },
        owned: {
            items: {
                '$ref': '#/components/schemas/OwnedPropertyPublic'
            },
            type: 'array',
            title: 'Owned'
        }
    },
    type: 'object',
    required: ['tiers', 'owned'],
    title: 'PropertiesListResponse'
} as const;

export const PropertyTierPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        svg_key: {
            type: 'string',
            title: 'Svg Key'
        },
        price: {
            type: 'integer',
            title: 'Price'
        },
        daily_income: {
            type: 'integer',
            title: 'Daily Income'
        },
        unlock_level: {
            type: 'integer',
            title: 'Unlock Level'
        }
    },
    type: 'object',
    required: ['id', 'name', 'svg_key', 'price', 'daily_income', 'unlock_level'],
    title: 'PropertyTierPublic'
} as const;

export const QuizAnswerItemSchema = {
    properties: {
        case_id: {
            type: 'integer',
            title: 'Case Id'
        },
        guess_is_scam: {
            type: 'boolean',
            title: 'Guess Is Scam'
        }
    },
    type: 'object',
    required: ['case_id', 'guess_is_scam'],
    title: 'QuizAnswerItem'
} as const;

export const QuizAnswerRequestSchema = {
    properties: {
        case_id: {
            type: 'integer',
            title: 'Case Id'
        },
        guess_is_scam: {
            type: 'boolean',
            title: 'Guess Is Scam'
        }
    },
    type: 'object',
    required: ['case_id', 'guess_is_scam'],
    title: 'QuizAnswerRequest'
} as const;

export const QuizAnswerResponseSchema = {
    properties: {
        correct: {
            type: 'boolean',
            title: 'Correct'
        },
        is_scam: {
            type: 'boolean',
            title: 'Is Scam'
        },
        red_flags: {
            items: {
                '$ref': '#/components/schemas/QuizRedFlag'
            },
            type: 'array',
            title: 'Red Flags'
        },
        provenance: {
            type: 'string',
            title: 'Provenance'
        }
    },
    type: 'object',
    required: ['correct', 'is_scam', 'red_flags', 'provenance'],
    title: 'QuizAnswerResponse'
} as const;

export const QuizCasePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        fraud_type: {
            type: 'string',
            title: 'Fraud Type'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        narrative: {
            type: 'string',
            title: 'Narrative'
        },
        difficulty: {
            type: 'integer',
            title: 'Difficulty'
        }
    },
    type: 'object',
    required: ['id', 'fraud_type', 'title', 'narrative', 'difficulty'],
    title: 'QuizCasePublic'
} as const;

export const QuizCompleteRequestSchema = {
    properties: {
        answers: {
            items: {
                '$ref': '#/components/schemas/QuizAnswerItem'
            },
            type: 'array',
            title: 'Answers'
        }
    },
    type: 'object',
    required: ['answers'],
    title: 'QuizCompleteRequest'
} as const;

export const QuizCompleteResponseSchema = {
    properties: {
        correct_count: {
            type: 'integer',
            title: 'Correct Count'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        best_streak: {
            type: 'integer',
            title: 'Best Streak'
        },
        cash_earned: {
            type: 'integer',
            title: 'Cash Earned'
        },
        xp_earned: {
            type: 'integer',
            title: 'Xp Earned'
        },
        weakness_summary: {
            items: {
                '$ref': '#/components/schemas/WeaknessSummaryItem'
            },
            type: 'array',
            title: 'Weakness Summary'
        }
    },
    type: 'object',
    required: ['correct_count', 'total', 'best_streak', 'cash_earned', 'xp_earned', 'weakness_summary'],
    title: 'QuizCompleteResponse'
} as const;

export const QuizRedFlagSchema = {
    properties: {
        tag: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tag'
        },
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: ['tag', 'text'],
    title: 'QuizRedFlag'
} as const;

export const ScenarioDetailSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        fraud_type: {
            type: 'string',
            title: 'Fraud Type'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        avatar: {
            type: 'string',
            title: 'Avatar'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        outcome: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Outcome'
        },
        player_turns: {
            type: 'integer',
            title: 'Player Turns'
        },
        max_turns: {
            type: 'integer',
            title: 'Max Turns'
        },
        history: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'History'
        }
    },
    type: 'object',
    required: ['id', 'fraud_type', 'display_name', 'avatar', 'status', 'outcome', 'player_turns', 'max_turns', 'history'],
    title: 'ScenarioDetail'
} as const;

export const ScenarioInboxItemSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        fraud_type: {
            type: 'string',
            title: 'Fraud Type'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        avatar: {
            type: 'string',
            title: 'Avatar'
        },
        preview: {
            type: 'string',
            title: 'Preview'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        outcome: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Outcome'
        },
        unread: {
            type: 'boolean',
            title: 'Unread'
        }
    },
    type: 'object',
    required: ['id', 'fraud_type', 'display_name', 'avatar', 'preview', 'status', 'outcome', 'unread'],
    title: 'ScenarioInboxItem'
} as const;

export const ScenarioJudgeRequestSchema = {
    properties: {
        action: {
            type: 'string',
            enum: ['report', 'comply'],
            title: 'Action'
        }
    },
    type: 'object',
    required: ['action'],
    title: 'ScenarioJudgeRequest'
} as const;

export const ScenarioJudgeResponseSchema = {
    properties: {
        outcome: {
            type: 'string',
            title: 'Outcome'
        },
        true_role: {
            type: 'string',
            title: 'True Role'
        },
        persona_name: {
            type: 'string',
            title: 'Persona Name'
        },
        flags: {
            items: {
                '$ref': '#/components/schemas/FlagItem'
            },
            type: 'array',
            title: 'Flags'
        },
        cash_delta: {
            type: 'integer',
            title: 'Cash Delta'
        },
        xp_delta: {
            type: 'integer',
            title: 'Xp Delta'
        },
        new_cash: {
            type: 'integer',
            title: 'New Cash'
        },
        triggers_forced_sell: {
            type: 'boolean',
            title: 'Triggers Forced Sell'
        },
        case_provenance: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Case Provenance'
        }
    },
    type: 'object',
    required: ['outcome', 'true_role', 'persona_name', 'flags', 'cash_delta', 'xp_delta', 'new_cash', 'triggers_forced_sell', 'case_provenance'],
    title: 'ScenarioJudgeResponse'
} as const;

export const ScenarioMessageRequestSchema = {
    properties: {
        text: {
            type: 'string',
            maxLength: 2000,
            title: 'Text'
        }
    },
    type: 'object',
    required: ['text'],
    title: 'ScenarioMessageRequest'
} as const;

export const ScenarioMessageResponseSchema = {
    properties: {
        messages: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Messages'
        },
        decision_point: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Decision Point'
        },
        turns_left: {
            type: 'integer',
            title: 'Turns Left'
        }
    },
    type: 'object',
    required: ['messages', 'decision_point', 'turns_left'],
    title: 'ScenarioMessageResponse'
} as const;

export const ScenarioNewRequestSchema = {
    properties: {
        fraud_type: {
            type: 'string',
            title: 'Fraud Type'
        }
    },
    type: 'object',
    required: ['fraud_type'],
    title: 'ScenarioNewRequest'
} as const;

export const SwipeAnswerItemSchema = {
    properties: {
        card_id: {
            type: 'string',
            title: 'Card Id'
        },
        guess_is_scam: {
            type: 'boolean',
            title: 'Guess Is Scam'
        }
    },
    type: 'object',
    required: ['card_id', 'guess_is_scam'],
    title: 'SwipeAnswerItem'
} as const;

export const SwipeAnswerRequestSchema = {
    properties: {
        card_id: {
            type: 'string',
            title: 'Card Id'
        },
        guess_is_scam: {
            type: 'boolean',
            title: 'Guess Is Scam'
        }
    },
    type: 'object',
    required: ['card_id', 'guess_is_scam'],
    title: 'SwipeAnswerRequest'
} as const;

export const SwipeAnswerResponseSchema = {
    properties: {
        correct: {
            type: 'boolean',
            title: 'Correct'
        },
        is_scam: {
            type: 'boolean',
            title: 'Is Scam'
        },
        explanation: {
            type: 'string',
            title: 'Explanation'
        },
        weakness_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Weakness Tags'
        }
    },
    type: 'object',
    required: ['correct', 'is_scam', 'explanation', 'weakness_tags'],
    title: 'SwipeAnswerResponse'
} as const;

export const SwipeCardPublicSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        scenario: {
            type: 'string',
            title: 'Scenario'
        },
        source_label: {
            type: 'string',
            title: 'Source Label'
        },
        fraud_type: {
            type: 'string',
            title: 'Fraud Type'
        },
        difficulty: {
            type: 'integer',
            title: 'Difficulty'
        }
    },
    type: 'object',
    required: ['id', 'scenario', 'source_label', 'fraud_type', 'difficulty'],
    title: 'SwipeCardPublic'
} as const;

export const SwipeCompleteRequestSchema = {
    properties: {
        answers: {
            items: {
                '$ref': '#/components/schemas/SwipeAnswerItem'
            },
            type: 'array',
            title: 'Answers'
        }
    },
    type: 'object',
    required: ['answers'],
    title: 'SwipeCompleteRequest'
} as const;

export const SwipeCompleteResponseSchema = {
    properties: {
        correct_count: {
            type: 'integer',
            title: 'Correct Count'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        best_streak: {
            type: 'integer',
            title: 'Best Streak'
        },
        cash_earned: {
            type: 'integer',
            title: 'Cash Earned'
        },
        xp_earned: {
            type: 'integer',
            title: 'Xp Earned'
        },
        weakness_summary: {
            items: {
                '$ref': '#/components/schemas/WeaknessSummaryItem'
            },
            type: 'array',
            title: 'Weakness Summary'
        }
    },
    type: 'object',
    required: ['correct_count', 'total', 'best_streak', 'cash_earned', 'xp_earned', 'weakness_summary'],
    title: 'SwipeCompleteResponse'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WeaknessDetailSchema = {
    properties: {
        tag: {
            type: 'string',
            title: 'Tag'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        suggestion: {
            type: 'string',
            title: 'Suggestion'
        }
    },
    type: 'object',
    required: ['tag', 'count', 'label', 'suggestion'],
    title: 'WeaknessDetail'
} as const;

export const WeaknessSummaryItemSchema = {
    properties: {
        tag: {
            type: 'string',
            title: 'Tag'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['tag', 'count'],
    title: 'WeaknessSummaryItem'
} as const;