// This file is auto-generated by @hey-api/openapi-ts

export type AssetSummaryResponse = {
    cash: number;
    property_value: number;
    daily_income: number;
    total_net_worth: number;
    owned_count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BuyPropertyResponse = {
    property_id: string;
    new_cash: number;
};

export type ChapterMilestonePublic = {
    chapter_id: number;
    title: string;
    skill_type: string;
    description: string;
    quiz_completed: boolean;
    scenario_completed: boolean;
    is_completed: boolean;
    is_current: boolean;
};

export type ChapterStatusResponse = {
    completed_chapters: number;
    income_multiplier: number;
    starter_grant_claimed: boolean;
    can_claim_starter_grant: boolean;
    chapters: Array<ChapterMilestonePublic>;
};

export type ClaimStarterGrantResponse = {
    granted_cash: number;
    new_cash: number;
};

export type EconomyMeResponse = {
    cash: number;
    xp: number;
    level: number;
    streak_days: number;
    pending_accrual: number;
    bankruptcy_pending: boolean;
    completed_chapters?: number;
};

export type FlagItem = {
    tag: (string | null);
    label: string;
    detail: string;
};

export type FraudTypeResult = {
    correct: number;
    total: number;
};

export type HomeDecorActionRequest = {
    decor_id: string;
};

export type HomeDecorItemPublic = {
    id: string;
    name: string;
    cost: number;
    description: string;
    icon: string;
    is_owned: boolean;
    is_equipped: boolean;
};

export type HomeFollowUpEventResponse = {
    event_id: string;
    title: string;
    scenario: string;
    verification_step: string;
    evidence: string;
    is_completed: boolean;
};

export type HouseTaskPublic = {
    task_id: string;
    tier_id: number;
    title: string;
    scenario: string;
    steps: Array<HouseTaskStepPublic>;
    is_passed: boolean;
    can_proceed_to_buy: boolean;
};

export type HouseTaskResolveRequest = {
    choice: 'official_escrow' | 'private_wire';
};

export type choice = 'official_escrow' | 'private_wire';

export type HouseTaskResolveResponse = {
    is_passed: boolean;
    message: string;
    can_buy: boolean;
};

export type HouseTaskStepPublic = {
    step_id: string;
    name: string;
    description: string;
    evidence?: (string | null);
    is_done?: boolean;
};

export type HouseTaskVerifyRequest = {
    step_id: string;
};

export type HouseTaskVerifyResponse = {
    step_id: string;
    evidence: string;
    all_steps_done: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LiquidateRequest = {
    property_ids: Array<(string)>;
};

export type LiquidateResponse = {
    recovered: number;
    new_cash: number;
    bankruptcy_pending: boolean;
};

export type Message = {
    message: string;
};

export type MyHomeResponse = {
    has_house: boolean;
    house_count: number;
    best_tier_name: (string | null);
    decorations: Array<HomeDecorItemPublic>;
    follow_up_event_unlocked: boolean;
    follow_up_event_title: (string | null);
    follow_up_event_done: boolean;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OwnedPropertyPublic = {
    id: string;
    tier: PropertyTierPublic;
    purchased_at: string;
    purchase_price?: number;
};

export type PretestAnswer = {
    question_id: string;
    selected_option: string;
};

export type PretestSubmitRequest = {
    answers: Array<PretestAnswer>;
};

export type PretestSubmitResponse = {
    results_by_type: {
        [key: string]: FraudTypeResult;
    };
    weakest_type: string;
    ready_for_game: boolean;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type PropertiesListResponse = {
    tiers: Array<PropertyTierPublic>;
    owned: Array<OwnedPropertyPublic>;
};

export type PropertyTierPublic = {
    id: number;
    name: string;
    svg_key: string;
    price: number;
    daily_income: number;
    unlock_level: number;
};

export type QuizAnswerRequest = {
    item_id: string;
    guess_is_scam?: (boolean | null);
    selected_option?: (string | null);
    selected_tags?: (Array<(string)> | null);
    pairs?: ({
    [key: string]: (string);
} | null);
    session_id: string;
};

export type QuizCompleteRequest = {
    session_id: string;
};

export type QuizCompleteResponse = {
    correct_count: number;
    total: number;
    best_streak: number;
    cash_earned: number;
    xp_earned: number;
    weakness_summary: Array<WeaknessSummaryItem>;
};

export type QuizDeckResponse = {
    session_id: string;
    items: Array<(QuizVerdictPublic | QuizVerificationPublic | QuizTacticsPublic | QuizMatchPublic)>;
};

export type QuizMatchAnswerResponse = {
    type?: "match";
    correct: boolean;
    results: Array<QuizMatchPairResult>;
    tag_details: Array<QuizWeaknessDetail>;
};

export type QuizMatchPairResult = {
    pair_id: string;
    correct_tag: string;
    correct: boolean;
};

export type QuizMatchPrompt = {
    pair_id: string;
    text: string;
};

export type QuizMatchPublic = {
    item_id: string;
    type?: "match";
    question: string;
    match_prompts: Array<QuizMatchPrompt>;
    match_targets: Array<QuizMatchTarget>;
};

export type QuizMatchTarget = {
    tag: string;
    label: string;
};

export type QuizRedFlag = {
    tag: (string | null);
    text: string;
};

export type QuizTacticsAnswerResponse = {
    type?: "tactics";
    correct: boolean;
    correct_tags: Array<(string)>;
    missed_tags: Array<(string)>;
    extra_tags: Array<(string)>;
    tag_details: Array<QuizWeaknessDetail>;
};

export type QuizTacticsOption = {
    tag: string;
    label: string;
};

export type QuizTacticsPublic = {
    item_id: string;
    type?: "tactics";
    title: string;
    narrative: string;
    question: string;
    options: Array<QuizTacticsOption>;
};

export type QuizVerdictAnswerResponse = {
    type?: "verdict";
    correct: boolean;
    is_scam: boolean;
    red_flags: Array<QuizRedFlag>;
    provenance: string;
    tag_details: Array<QuizWeaknessDetail>;
};

export type QuizVerdictPublic = {
    item_id: string;
    type?: "verdict";
    title: string;
    narrative: string;
};

export type QuizVerificationAnswerResponse = {
    type?: "verification";
    correct: boolean;
    explanation: string;
    tag_details: Array<QuizWeaknessDetail>;
};

export type QuizVerificationOption = {
    key: string;
    text: string;
};

export type QuizVerificationPublic = {
    item_id: string;
    type?: "verification";
    title: string;
    narrative: string;
    question: string;
    options: Array<QuizVerificationOption>;
};

export type QuizWeaknessDetail = {
    tag: string;
    label: string;
    suggestion: string;
};

export type ScenarioDetail = {
    id: string;
    fraud_type: string;
    display_name: string;
    avatar: string;
    status: string;
    outcome: (string | null);
    player_turns: number;
    max_turns: number;
    history: Array<{
        [key: string]: unknown;
    }>;
    available_tools?: Array<ScenarioToolItem>;
    unlocked_evidence?: Array<ScenarioEvidenceItem>;
};

export type ScenarioEvidenceItem = {
    tool_id: string;
    title: string;
    content: string;
};

export type ScenarioInboxItem = {
    id: string;
    fraud_type: string;
    display_name: string;
    avatar: string;
    preview: string;
    status: string;
    outcome: (string | null);
    unread: boolean;
};

export type ScenarioJudgeRequest = {
    action: 'report' | 'comply' | 'safe_exit';
};

export type action = 'report' | 'comply' | 'safe_exit';

export type ScenarioJudgeResponse = {
    outcome: string;
    true_role: string;
    persona_name: string;
    flags: Array<FlagItem>;
    cash_delta: number;
    xp_delta: number;
    new_cash: number;
    triggers_forced_sell: boolean;
    case_provenance: (string | null);
    unlocked_evidence_count?: number;
};

export type ScenarioMessageRequest = {
    text: string;
};

export type ScenarioMessageResponse = {
    messages: Array<(string)>;
    decision_point: (string | null);
    turns_left: number;
};

export type ScenarioNewRequest = {
    fraud_type: string;
};

export type ScenarioToolItem = {
    tool_id: string;
    name: string;
    description: string;
};

export type ScenarioVerifyRequest = {
    tool_id: string;
};

export type ScenarioVerifyResponse = {
    evidence: ScenarioEvidenceItem;
    already_unlocked: boolean;
    unlocked_evidence: Array<ScenarioEvidenceItem>;
};

export type SwipeAnswerRequest = {
    session_id: string;
    card_id: string;
    guess_is_scam?: (boolean | null);
    action?: ('scam' | 'legit' | 'skip' | null);
};

export type SwipeAnswerResponse = {
    correct: boolean;
    is_scam: boolean;
    action_taken: string;
    explanation: string;
    weakness_tags: Array<(string)>;
    tag_details: Array<QuizWeaknessDetail>;
};

export type SwipeCardPublic = {
    id: string;
    scenario: string;
};

export type SwipeCompleteRequest = {
    session_id: string;
};

export type SwipeCompleteResponse = {
    correct_count: number;
    total: number;
    best_streak: number;
    cash_earned: number;
    xp_earned: number;
    weakness_summary: Array<WeaknessSummaryItem>;
};

export type SwipeDeckResponse = {
    session_id: string;
    cards: Array<SwipeCardPublic>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VehiclePublic = {
    name: string;
    price: number;
    is_owned: boolean;
    purchased_at: (string | null);
    follow_up_event_title: string;
    follow_up_event_done: boolean;
};

export type WeaknessSummaryItem = {
    tag: string;
    label: string;
    count: number;
};

export type EconomyReadMeResponse = (EconomyMeResponse);

export type EconomyPostSettleResponse = (EconomyMeResponse);

export type EconomyClaimResponse = (EconomyMeResponse);

export type EconomyListPropertiesResponse = (PropertiesListResponse);

export type EconomyBuyPropertyData = {
    tierId: number;
};

export type EconomyBuyPropertyResponse = (BuyPropertyResponse);

export type EconomyGetAssetsResponse = (AssetSummaryResponse);

export type EconomyPostLiquidateData = {
    requestBody: LiquidateRequest;
};

export type EconomyPostLiquidateResponse = (LiquidateResponse);

export type EconomyGetChaptersResponse = (ChapterStatusResponse);

export type EconomyPostClaimStarterGrantResponse = (ClaimStarterGrantResponse);

export type EconomyGetHouseTaskResponse = (HouseTaskPublic);

export type EconomyVerifyHouseTaskData = {
    requestBody: HouseTaskVerifyRequest;
};

export type EconomyVerifyHouseTaskResponse = (HouseTaskVerifyResponse);

export type EconomyResolveHouseTaskEndpointData = {
    requestBody: HouseTaskResolveRequest;
};

export type EconomyResolveHouseTaskEndpointResponse = (HouseTaskResolveResponse);

export type EconomyGetMyHomeResponse = (MyHomeResponse);

export type EconomyBuyHomeDecorData = {
    requestBody: HomeDecorActionRequest;
};

export type EconomyBuyHomeDecorResponse = (MyHomeResponse);

export type EconomyToggleHomeDecorData = {
    requestBody: HomeDecorActionRequest;
};

export type EconomyToggleHomeDecorResponse = (MyHomeResponse);

export type EconomyGetHomeEventResponse = (HomeFollowUpEventResponse);

export type EconomyResolveHomeEventResponse = (HomeFollowUpEventResponse);

export type EconomyGetVehicleResponse = (VehiclePublic);

export type EconomyBuyVehicleResponse = (VehiclePublic);

export type EconomyResolveVehicleEventResponse = (VehiclePublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MascotListMascotItemsResponse = (unknown);

export type MascotPurchaseItemData = {
    itemId: string;
};

export type MascotPurchaseItemResponse = (unknown);

export type MascotToggleEquipData = {
    itemId: string;
};

export type MascotToggleEquipResponse = (unknown);

export type MascotGetMyMascotResponse = (unknown);

export type PretestGetPretestQuestionsResponse = (unknown);

export type PretestSubmitPretestData = {
    requestBody: PretestSubmitRequest;
};

export type PretestSubmitPretestResponse = (PretestSubmitResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type QuickSwipeDeckData = {
    size?: number;
};

export type QuickSwipeDeckResponse = (SwipeDeckResponse);

export type QuickSwipeAnswerData = {
    requestBody: SwipeAnswerRequest;
};

export type QuickSwipeAnswerResponse = (SwipeAnswerResponse);

export type QuickSwipeCompleteData = {
    requestBody: SwipeCompleteRequest;
};

export type QuickSwipeCompleteResponse = (SwipeCompleteResponse);

export type QuickQuizDeckData = {
    size?: number;
};

export type QuickQuizDeckResponse = (QuizDeckResponse);

export type QuickQuizAnswerData = {
    requestBody: QuizAnswerRequest;
};

export type QuickQuizAnswerResponse = ((QuizVerdictAnswerResponse | QuizVerificationAnswerResponse | QuizTacticsAnswerResponse | QuizMatchAnswerResponse));

export type QuickQuizCompleteData = {
    requestBody: QuizCompleteRequest;
};

export type QuickQuizCompleteResponse = (QuizCompleteResponse);

export type ScenarioInboxResponse = (Array<ScenarioInboxItem>);

export type ScenarioCreateScenarioData = {
    requestBody: ScenarioNewRequest;
};

export type ScenarioCreateScenarioResponse = (ScenarioInboxItem);

export type ScenarioReadScenarioData = {
    scenarioId: string;
};

export type ScenarioReadScenarioResponse = (ScenarioDetail);

export type ScenarioSendMessageData = {
    requestBody: ScenarioMessageRequest;
    scenarioId: string;
};

export type ScenarioSendMessageResponse = (ScenarioMessageResponse);

export type ScenarioVerifyScenarioData = {
    requestBody: ScenarioVerifyRequest;
    scenarioId: string;
};

export type ScenarioVerifyScenarioResponse = (ScenarioVerifyResponse);

export type ScenarioJudgeScenarioData = {
    requestBody: ScenarioJudgeRequest;
    scenarioId: string;
};

export type ScenarioJudgeScenarioResponse = (ScenarioJudgeResponse);

export type ScoreGetMyScoreResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);