// This file is auto-generated by @hey-api/openapi-ts

export type AnswerRequest = {
    selected_option: string;
};

export type AnswerResponse = {
    answer_result: AnswerResult;
    mascot_popup?: (MascotPopup | null);
    next_question?: (GameResponse | null);
    game_over?: (GameOverResult | null);
};

export type AnswerResult = {
    is_correct: boolean;
    correct_option: string;
    explanation: string;
    score_earned: number;
    total_score: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type FraudTypeResult = {
    correct: number;
    total: number;
};

export type GameOption = {
    key: string;
    text: string;
};

export type GameOverResult = {
    total_score: number;
    correct_rate: number;
    grade: string;
    weakness_analysis: Array<WeaknessDetail>;
    strength_tags: Array<(string)>;
};

/**
 * Agent 每步回傳的統一格式
 */
export type GameResponse = {
    question_type: 'scenario' | 'judgment' | 'trap';
    narrative: string;
    question: string;
    options: Array<GameOption>;
    correct_option: string;
    explanation: string;
    weakness_tag: (string | null);
    difficulty: number;
};

export type question_type = 'scenario' | 'judgment' | 'trap';

export type GameStartRequest = {
    fraud_type?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type MascotPopup = {
    show: boolean;
    message: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PretestAnswer = {
    question_id: string;
    selected_option: string;
};

export type PretestSubmitRequest = {
    answers: Array<PretestAnswer>;
};

export type PretestSubmitResponse = {
    results_by_type: {
        [key: string]: FraudTypeResult;
    };
    weakest_type: string;
    ready_for_game: boolean;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WeaknessDetail = {
    tag: string;
    count: number;
    label: string;
    suggestion: string;
};

export type GameStartGameData = {
    requestBody: GameStartRequest;
};

export type GameStartGameResponse = (unknown);

export type GameSubmitAnswerData = {
    requestBody: AnswerRequest;
    sessionId: string;
};

export type GameSubmitAnswerResponse = (AnswerResponse);

export type GameGetGameSessionData = {
    sessionId: string;
};

export type GameGetGameSessionResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MascotListMascotItemsResponse = (unknown);

export type MascotPurchaseItemData = {
    itemId: string;
};

export type MascotPurchaseItemResponse = (unknown);

export type MascotToggleEquipData = {
    itemId: string;
};

export type MascotToggleEquipResponse = (unknown);

export type MascotGetMyMascotResponse = (unknown);

export type PretestGetPretestQuestionsResponse = (unknown);

export type PretestSubmitPretestData = {
    requestBody: PretestSubmitRequest;
};

export type PretestSubmitPretestResponse = (PretestSubmitResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ScoreGetMyScoreResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);