"""add daily training

Revision ID: 078c2bab6834
Revises: f26a0c960771
Create Date: 2026-09-27 17:11:51.326002

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '078c2bab6834'
down_revision = 'f26a0c960771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_challenge',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('case_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('public_items', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('daily_result',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day')
    )
    op.create_index(op.f('ix_daily_result_day'), 'daily_result', ['day'], unique=False)
    op.add_column('quiz_session', sa.Column('daily_date', sa.Date(), nullable=True))
    op.create_index('uq_quiz_session_user_daily', 'quiz_session', ['user_id', 'daily_date'], unique=True, postgresql_where=sa.text('daily_date IS NOT NULL'))
    op.add_column('user', sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nickname')
    op.drop_index('uq_quiz_session_user_daily', table_name='quiz_session', postgresql_where=sa.text('daily_date IS NOT NULL'))
    op.drop_column('quiz_session', 'daily_date')
    op.drop_index(op.f('ix_daily_result_day'), table_name='daily_result')
    op.drop_table('daily_result')
    op.drop_table('daily_challenge')
    # ### end Alembic commands ###
