"""add anti-fraud game tables

Revision ID: 283a0751f0f8
Revises: fe56fa70289e
Create Date: 2026-04-05 14:09:30.930762

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '283a0751f0f8'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascot_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pretest_question',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fraud_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pretest_question_fraud_type'), 'pretest_question', ['fraud_type'], unique=False)
    op.create_table('game_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fraud_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_correct', sa.Integer(), nullable=False),
    sa.Column('total_wrong', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('conversation_history', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_session_fraud_type'), 'game_session', ['fraud_type'], unique=False)
    op.create_table('pretest_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fraud_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('selected_option', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['pretest_question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_mascot_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['mascot_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_score',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('game_answer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('question_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_option', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('correct_option', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('ai_explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weakness_tag', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_answer')
    op.drop_table('user_score')
    op.drop_table('user_mascot_item')
    op.drop_table('pretest_result')
    op.drop_index(op.f('ix_game_session_fraud_type'), table_name='game_session')
    op.drop_table('game_session')
    op.drop_index(op.f('ix_pretest_question_fraud_type'), table_name='pretest_question')
    op.drop_table('pretest_question')
    op.drop_table('mascot_item')
    # ### end Alembic commands ###
