"""add economy tables

Revision ID: 2c1ece4d94bc
Revises: 283a0751f0f8
Create Date: 2026-05-31 14:53:57.635021

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2c1ece4d94bc'
down_revision = '283a0751f0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_tier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('svg_key', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('daily_income', sa.Integer(), nullable=False),
    sa.Column('unlock_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_property',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['property_tier.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_property_user_id'), 'user_property', ['user_id'], unique=False)
    op.add_column('user', sa.Column('cash', sa.Integer(), nullable=False, server_default='1000'))
    op.add_column('user', sa.Column('xp', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('streak_days', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('streak_last_day', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('pending_accrual', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('last_settled_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('user', sa.Column('bankruptcy_pending', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('user', sa.Column('bankruptcy_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bankruptcy_count')
    op.drop_column('user', 'bankruptcy_pending')
    op.drop_column('user', 'last_settled_at')
    op.drop_column('user', 'pending_accrual')
    op.drop_column('user', 'streak_last_day')
    op.drop_column('user', 'streak_days')
    op.drop_column('user', 'xp')
    op.drop_column('user', 'cash')
    op.drop_index(op.f('ix_user_property_user_id'), table_name='user_property')
    op.drop_table('user_property')
    op.drop_table('property_tier')
    # ### end Alembic commands ###
