"""add practice log, profile and seed keys

Revision ID: 97fd54061f12
Revises: fdeaba1c2ecd
Create Date: 2026-09-24 23:28:40.217491

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97fd54061f12'
down_revision = 'fdeaba1c2ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_answer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('fraud_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('missed_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_answer_created_at'), 'practice_answer', ['created_at'], unique=False)
    op.create_index(op.f('ix_practice_answer_user_id'), 'practice_answer', ['user_id'], unique=False)
    op.create_table('practice_profile',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('focus_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('answers_seen', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('pretest_question', sa.Column('seed_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('pretest_question', sa.Column('is_scam', sa.Boolean(), nullable=True))
    op.create_unique_constraint('uq_pretest_question_seed_key', 'pretest_question', ['seed_key'])
    op.add_column('swipe_card', sa.Column('seed_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.create_unique_constraint('uq_swipe_card_seed_key', 'swipe_card', ['seed_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_swipe_card_seed_key', 'swipe_card', type_='unique')
    op.drop_column('swipe_card', 'seed_key')
    op.drop_constraint('uq_pretest_question_seed_key', 'pretest_question', type_='unique')
    op.drop_column('pretest_question', 'is_scam')
    op.drop_column('pretest_question', 'seed_key')
    op.drop_table('practice_profile')
    op.drop_index(op.f('ix_practice_answer_user_id'), table_name='practice_answer')
    op.drop_index(op.f('ix_practice_answer_created_at'), table_name='practice_answer')
    op.drop_table('practice_answer')
    # ### end Alembic commands ###
