"""add swipe_card

Revision ID: be9065cabe74
Revises: 2c1ece4d94bc
Create Date: 2026-06-23 17:42:24.822666

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be9065cabe74'
down_revision = '2c1ece4d94bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swipe_card',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_label', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('is_scam', sa.Boolean(), nullable=False),
    sa.Column('fraud_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('weakness_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swipe_card_fraud_type'), 'swipe_card', ['fraud_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swipe_card_fraud_type'), table_name='swipe_card')
    op.drop_table('swipe_card')
    # ### end Alembic commands ###
