"""add scenario_session

Revision ID: c88095cb408d
Revises: be9065cabe74
Create Date: 2026-07-02 09:23:22.868072

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c88095cb408d'
down_revision = 'be9065cabe74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fraud_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('persona_role', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('conversation_history', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('player_turns', sa.Integer(), nullable=False),
    sa.Column('tactics_seen', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('stake_loss', sa.Integer(), nullable=False),
    sa.Column('reward_win', sa.Integer(), nullable=False),
    sa.Column('reward_legit', sa.Integer(), nullable=False),
    sa.Column('penalty_misreport', sa.Integer(), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_session_fraud_type'), 'scenario_session', ['fraud_type'], unique=False)
    op.create_index(op.f('ix_scenario_session_user_id'), 'scenario_session', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_session_user_id'), table_name='scenario_session')
    op.drop_index(op.f('ix_scenario_session_fraud_type'), table_name='scenario_session')
    op.drop_table('scenario_session')
    # ### end Alembic commands ###
