"""add scenario_session case_id

Revision ID: caf510034843
Revises: c88095cb408d
Create Date: 2026-07-03 21:48:21.585467

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'caf510034843'
down_revision = 'c88095cb408d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_session', sa.Column('case_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_session', 'case_id')
    # ### end Alembic commands ###
