"""add pretest_attempt

Revision ID: fdeaba1c2ecd
Revises: e7a3c91d5f20
Create Date: 2026-09-24 22:56:44.027069

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fdeaba1c2ecd'
down_revision = 'e7a3c91d5f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pretest_attempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('weakest_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pretest_attempt_user_id'), 'pretest_attempt', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pretest_attempt_user_id'), table_name='pretest_attempt')
    op.drop_table('pretest_attempt')
    # ### end Alembic commands ###
