/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as PretestRouteImport } from './routes/pretest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as PretestResultRouteImport } from './routes/pretest.result'
import { Route as GameSessionIdRouteImport } from './routes/game.$sessionId'
import { Route as ShellMeRouteImport } from './routes/_shell/me'
import { Route as ShellAssetsRouteImport } from './routes/_shell/assets'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutMascotRouteImport } from './routes/_layout/mascot'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as ShellScenariosIndexRouteImport } from './routes/_shell/scenarios/index'
import { Route as GameSessionIdResultRouteImport } from './routes/game.$sessionId.result'
import { Route as ShellScenariosScenarioIdRouteImport } from './routes/_shell/scenarios/$scenarioId'
import { Route as ShellQuickSwipeRouteImport } from './routes/_shell/quick/swipe'
import { Route as ShellQuickQuizRouteImport } from './routes/_shell/quick/quiz'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PretestRoute = PretestRouteImport.update({
  id: '/pretest',
  path: '/pretest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const PretestResultRoute = PretestResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => PretestRoute,
} as any)
const GameSessionIdRoute = GameSessionIdRouteImport.update({
  id: '/game/$sessionId',
  path: '/game/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellMeRoute = ShellMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssetsRoute = ShellAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => ShellRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMascotRoute = LayoutMascotRouteImport.update({
  id: '/mascot',
  path: '/mascot',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const ShellScenariosIndexRoute = ShellScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => ShellRoute,
} as any)
const GameSessionIdResultRoute = GameSessionIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => GameSessionIdRoute,
} as any)
const ShellScenariosScenarioIdRoute =
  ShellScenariosScenarioIdRouteImport.update({
    id: '/scenarios/$scenarioId',
    path: '/scenarios/$scenarioId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellQuickSwipeRoute = ShellQuickSwipeRouteImport.update({
  id: '/quick/swipe',
  path: '/quick/swipe',
  getParentRoute: () => ShellRoute,
} as any)
const ShellQuickQuizRoute = ShellQuickQuizRouteImport.update({
  id: '/quick/quiz',
  path: '/quick/quiz',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/pretest': typeof PretestRouteWithChildren
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/mascot': typeof LayoutMascotRoute
  '/settings': typeof LayoutSettingsRoute
  '/assets': typeof ShellAssetsRoute
  '/me': typeof ShellMeRoute
  '/game/$sessionId': typeof GameSessionIdRouteWithChildren
  '/pretest/result': typeof PretestResultRoute
  '/quick/quiz': typeof ShellQuickQuizRoute
  '/quick/swipe': typeof ShellQuickSwipeRoute
  '/scenarios/$scenarioId': typeof ShellScenariosScenarioIdRoute
  '/game/$sessionId/result': typeof GameSessionIdResultRoute
  '/scenarios/': typeof ShellScenariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/pretest': typeof PretestRouteWithChildren
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/mascot': typeof LayoutMascotRoute
  '/settings': typeof LayoutSettingsRoute
  '/assets': typeof ShellAssetsRoute
  '/me': typeof ShellMeRoute
  '/game/$sessionId': typeof GameSessionIdRouteWithChildren
  '/pretest/result': typeof PretestResultRoute
  '/quick/quiz': typeof ShellQuickQuizRoute
  '/quick/swipe': typeof ShellQuickSwipeRoute
  '/scenarios/$scenarioId': typeof ShellScenariosScenarioIdRoute
  '/game/$sessionId/result': typeof GameSessionIdResultRoute
  '/scenarios': typeof ShellScenariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/pretest': typeof PretestRouteWithChildren
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/mascot': typeof LayoutMascotRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_shell/assets': typeof ShellAssetsRoute
  '/_shell/me': typeof ShellMeRoute
  '/game/$sessionId': typeof GameSessionIdRouteWithChildren
  '/pretest/result': typeof PretestResultRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/quick/quiz': typeof ShellQuickQuizRoute
  '/_shell/quick/swipe': typeof ShellQuickSwipeRoute
  '/_shell/scenarios/$scenarioId': typeof ShellScenariosScenarioIdRoute
  '/game/$sessionId/result': typeof GameSessionIdResultRoute
  '/_shell/scenarios/': typeof ShellScenariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pretest'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/mascot'
    | '/settings'
    | '/assets'
    | '/me'
    | '/game/$sessionId'
    | '/pretest/result'
    | '/quick/quiz'
    | '/quick/swipe'
    | '/scenarios/$scenarioId'
    | '/game/$sessionId/result'
    | '/scenarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pretest'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/mascot'
    | '/settings'
    | '/assets'
    | '/me'
    | '/game/$sessionId'
    | '/pretest/result'
    | '/quick/quiz'
    | '/quick/swipe'
    | '/scenarios/$scenarioId'
    | '/game/$sessionId/result'
    | '/scenarios'
  id:
    | '__root__'
    | '/_layout'
    | '/_shell'
    | '/login'
    | '/pretest'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/mascot'
    | '/_layout/settings'
    | '/_shell/assets'
    | '/_shell/me'
    | '/game/$sessionId'
    | '/pretest/result'
    | '/_shell/'
    | '/_shell/quick/quiz'
    | '/_shell/quick/swipe'
    | '/_shell/scenarios/$scenarioId'
    | '/game/$sessionId/result'
    | '/_shell/scenarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  PretestRoute: typeof PretestRouteWithChildren
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  GameSessionIdRoute: typeof GameSessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretest': {
      id: '/pretest'
      path: '/pretest'
      fullPath: '/pretest'
      preLoaderRoute: typeof PretestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/pretest/result': {
      id: '/pretest/result'
      path: '/result'
      fullPath: '/pretest/result'
      preLoaderRoute: typeof PretestResultRouteImport
      parentRoute: typeof PretestRoute
    }
    '/game/$sessionId': {
      id: '/game/$sessionId'
      path: '/game/$sessionId'
      fullPath: '/game/$sessionId'
      preLoaderRoute: typeof GameSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/me': {
      id: '/_shell/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof ShellMeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assets': {
      id: '/_shell/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof ShellAssetsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mascot': {
      id: '/_layout/mascot'
      path: '/mascot'
      fullPath: '/mascot'
      preLoaderRoute: typeof LayoutMascotRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_shell/scenarios/': {
      id: '/_shell/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof ShellScenariosIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/game/$sessionId/result': {
      id: '/game/$sessionId/result'
      path: '/result'
      fullPath: '/game/$sessionId/result'
      preLoaderRoute: typeof GameSessionIdResultRouteImport
      parentRoute: typeof GameSessionIdRoute
    }
    '/_shell/scenarios/$scenarioId': {
      id: '/_shell/scenarios/$scenarioId'
      path: '/scenarios/$scenarioId'
      fullPath: '/scenarios/$scenarioId'
      preLoaderRoute: typeof ShellScenariosScenarioIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/quick/swipe': {
      id: '/_shell/quick/swipe'
      path: '/quick/swipe'
      fullPath: '/quick/swipe'
      preLoaderRoute: typeof ShellQuickSwipeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/quick/quiz': {
      id: '/_shell/quick/quiz'
      path: '/quick/quiz'
      fullPath: '/quick/quiz'
      preLoaderRoute: typeof ShellQuickQuizRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutMascotRoute: typeof LayoutMascotRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutMascotRoute: LayoutMascotRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface ShellRouteChildren {
  ShellAssetsRoute: typeof ShellAssetsRoute
  ShellMeRoute: typeof ShellMeRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellQuickQuizRoute: typeof ShellQuickQuizRoute
  ShellQuickSwipeRoute: typeof ShellQuickSwipeRoute
  ShellScenariosScenarioIdRoute: typeof ShellScenariosScenarioIdRoute
  ShellScenariosIndexRoute: typeof ShellScenariosIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAssetsRoute: ShellAssetsRoute,
  ShellMeRoute: ShellMeRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellQuickQuizRoute: ShellQuickQuizRoute,
  ShellQuickSwipeRoute: ShellQuickSwipeRoute,
  ShellScenariosScenarioIdRoute: ShellScenariosScenarioIdRoute,
  ShellScenariosIndexRoute: ShellScenariosIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface PretestRouteChildren {
  PretestResultRoute: typeof PretestResultRoute
}

const PretestRouteChildren: PretestRouteChildren = {
  PretestResultRoute: PretestResultRoute,
}

const PretestRouteWithChildren =
  PretestRoute._addFileChildren(PretestRouteChildren)

interface GameSessionIdRouteChildren {
  GameSessionIdResultRoute: typeof GameSessionIdResultRoute
}

const GameSessionIdRouteChildren: GameSessionIdRouteChildren = {
  GameSessionIdResultRoute: GameSessionIdResultRoute,
}

const GameSessionIdRouteWithChildren = GameSessionIdRoute._addFileChildren(
  GameSessionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  PretestRoute: PretestRouteWithChildren,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  GameSessionIdRoute: GameSessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
