/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as PretestRouteImport } from './routes/pretest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as PretestResultRouteImport } from './routes/pretest.result'
import { Route as GameSessionIdRouteImport } from './routes/game.$sessionId'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutMascotRouteImport } from './routes/_layout/mascot'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as GameSessionIdResultRouteImport } from './routes/game.$sessionId.result'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PretestRoute = PretestRouteImport.update({
  id: '/pretest',
  path: '/pretest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const PretestResultRoute = PretestResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => PretestRoute,
} as any)
const GameSessionIdRoute = GameSessionIdRouteImport.update({
  id: '/game/$sessionId',
  path: '/game/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMascotRoute = LayoutMascotRouteImport.update({
  id: '/mascot',
  path: '/mascot',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const GameSessionIdResultRoute = GameSessionIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => GameSessionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/pretest': typeof PretestRouteWithChildren
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/mascot': typeof LayoutMascotRoute
  '/settings': typeof LayoutSettingsRoute
  '/game/$sessionId': typeof GameSessionIdRouteWithChildren
  '/pretest/result': typeof PretestResultRoute
  '/game/$sessionId/result': typeof GameSessionIdResultRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/pretest': typeof PretestRouteWithChildren
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/mascot': typeof LayoutMascotRoute
  '/settings': typeof LayoutSettingsRoute
  '/game/$sessionId': typeof GameSessionIdRouteWithChildren
  '/pretest/result': typeof PretestResultRoute
  '/': typeof LayoutIndexRoute
  '/game/$sessionId/result': typeof GameSessionIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/pretest': typeof PretestRouteWithChildren
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/mascot': typeof LayoutMascotRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/game/$sessionId': typeof GameSessionIdRouteWithChildren
  '/pretest/result': typeof PretestResultRoute
  '/_layout/': typeof LayoutIndexRoute
  '/game/$sessionId/result': typeof GameSessionIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pretest'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/mascot'
    | '/settings'
    | '/game/$sessionId'
    | '/pretest/result'
    | '/game/$sessionId/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/pretest'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/mascot'
    | '/settings'
    | '/game/$sessionId'
    | '/pretest/result'
    | '/'
    | '/game/$sessionId/result'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/pretest'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/mascot'
    | '/_layout/settings'
    | '/game/$sessionId'
    | '/pretest/result'
    | '/_layout/'
    | '/game/$sessionId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  PretestRoute: typeof PretestRouteWithChildren
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  GameSessionIdRoute: typeof GameSessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretest': {
      id: '/pretest'
      path: '/pretest'
      fullPath: '/pretest'
      preLoaderRoute: typeof PretestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/pretest/result': {
      id: '/pretest/result'
      path: '/result'
      fullPath: '/pretest/result'
      preLoaderRoute: typeof PretestResultRouteImport
      parentRoute: typeof PretestRoute
    }
    '/game/$sessionId': {
      id: '/game/$sessionId'
      path: '/game/$sessionId'
      fullPath: '/game/$sessionId'
      preLoaderRoute: typeof GameSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mascot': {
      id: '/_layout/mascot'
      path: '/mascot'
      fullPath: '/mascot'
      preLoaderRoute: typeof LayoutMascotRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/game/$sessionId/result': {
      id: '/game/$sessionId/result'
      path: '/result'
      fullPath: '/game/$sessionId/result'
      preLoaderRoute: typeof GameSessionIdResultRouteImport
      parentRoute: typeof GameSessionIdRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutMascotRoute: typeof LayoutMascotRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutMascotRoute: LayoutMascotRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface PretestRouteChildren {
  PretestResultRoute: typeof PretestResultRoute
}

const PretestRouteChildren: PretestRouteChildren = {
  PretestResultRoute: PretestResultRoute,
}

const PretestRouteWithChildren =
  PretestRoute._addFileChildren(PretestRouteChildren)

interface GameSessionIdRouteChildren {
  GameSessionIdResultRoute: typeof GameSessionIdResultRoute
}

const GameSessionIdRouteChildren: GameSessionIdRouteChildren = {
  GameSessionIdResultRoute: GameSessionIdResultRoute,
}

const GameSessionIdRouteWithChildren = GameSessionIdRoute._addFileChildren(
  GameSessionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  PretestRoute: PretestRouteWithChildren,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  GameSessionIdRoute: GameSessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
